[build]
  publish = "dist/public"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Environment variables for production
# These should be set in Netlify dashboard:
# - ADMIN_PASSWORD: Password for admin panel access
# - TELEGRAM_BOT_TOKEN: Telegram bot token for sending messages
# - TELEGRAM_CHAT_ID: Telegram chat ID where messages should be sent
# - VITE_API_URL: Base URL for API calls (usually not needed for same-origin)

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
